import vm from 'node:vm';
import { BaseProvider } from '../base.js';
import { ProviderDetail, ProviderEpisode, ProviderItem, ResolvedStream } from '../../types/provider.js';
import { StremioContentType } from '../../types/stremio.js';
import { HttpClient, MOBILE_USER_AGENT } from '../../utils/http.js';
import { extractStreams } from '../../extractors/index.js';

export class FaselhdProvider extends BaseProvider {
  private readonly http = new HttpClient();
  id = 'faselhd';
  name = 'FaselHD (فاصل إعلاني)';
  lang = 'ar';
  mainUrl = 'https://www.fasel-hd.co';
  supportedTypes: StremioContentType[] = ['movie', 'series', 'anime'];
  constructor() { super(); this.initLogger(); }

  private fixUrl(url?: string, baseUrl = this.mainUrl): string {
    if (!url) return '';
    if (url.startsWith('//')) return `https:${url}`;
    if (/^https?:\/\//i.test(url)) return url;
    return `${baseUrl.replace(/\/$/, '')}/${url.replace(/^\//, '')}`;
  }
  private effectiveOrigin(url: string | undefined, fallback: string): string { try { return new URL(url || fallback).origin; } catch { return fallback.replace(/\/$/, ''); } }
  private brandVerified($: any): boolean { const t = $('title').text().toLowerCase(); const o = $('meta[property="og:site_name"]').attr('content')?.toLowerCase() || ''; return t.includes('fasel') || t.includes('فاصل') || o.includes('fasel') || o.includes('فاصل'); }
  private parserContractVerified($: any): boolean { return $('a[href*="/video/"],a[href*="/watch/"],a[href*="/series/"],a[href*="/movie/"],a[href*="/post/"],a[href*="watch.php?"],iframe,script').length > 0; }
  private identityVerified($: any): boolean { return this.brandVerified($) && this.parserContractVerified($); }
  private parseItems($: any, baseUrl: string, forcedType?: StremioContentType): ProviderItem[] { const out: ProviderItem[]=[]; const seen=new Set<string>(); const push=(href?:string,title?:string,poster?:string)=>{if(!href||!title)return;const url=this.fixUrl(href,baseUrl);if(seen.has(url))return;seen.add(url);const type=forcedType||(/series|episode|مسلسل|حلقة/i.test(`${url} ${title}`)?'series':'movie');out.push({id:this.formatId(url.replace(baseUrl,'')),provider:this.name,type,title:title.trim(),poster:this.fixUrl(poster,baseUrl),url});}; $('div.postDiv,article,.post,.item,.post-item').each((_:any,el:any)=>{const a=$(el).find('a').first(),img=$(el).find('img').first();push(a.attr('href'),$(el).find('h1,h2,h3,.post-title,.title').first().text().trim()||a.attr('title')||img.attr('alt')||a.text().trim(),img.attr('data-src')||img.attr('src'));}); $('a[href*="/video/"],a[href*="/watch/"],a[href*="/series/"],a[href*="/movie/"],a[href*="/post/"],a[href*="watch.php?"]').each((_:any,el:any)=>{const a=$(el),img=a.find('img').first();push(a.attr('href'),a.attr('title')||img.attr('alt')||a.text().trim(),img.attr('data-src')||img.attr('src'));}); return out; }
  private async verifyCanonicalDomain(baseUrl:string):Promise<boolean>{try{const allowed=new Set(['www.fasel-hd.co','fasel-hd.co','www.fasel-hd.com','fasel-hd.com','fasellhd.rest','fasellhd.baby']);const host=new URL(baseUrl).hostname;if(!allowed.has(host))return false;const r=await this.http.get(`${baseUrl}/`,{headers:{'User-Agent':MOBILE_USER_AGENT},timeout:7000});const origin=this.effectiveOrigin(r.url,baseUrl);const ok=r.status>=200&&r.status<400&&this.brandVerified(r.$)&&this.parserContractVerified(r.$);this.logger.debug(`FaselHD identity landing status=${r.status} finalHost=${new URL(origin).hostname} brand=${this.brandVerified(r.$)} parserContract=${this.parserContractVerified(r.$)} bytes=${r.text.length}`);return ok;}catch{return false;}}
  async searchInternal(query:string):Promise<ProviderItem[]>{return this.withHealthyDomain(async base=>{if(!await this.verifyCanonicalDomain(base))return{value:[],identityVerified:false};const r=await this.http.get(`${base}/?s=${encodeURIComponent(query)}`);const b=this.effectiveOrigin(r.url,base);return{value:this.parseItems(r.$,b),identityVerified:true};});}
  async getCatalogInternal(type:StremioContentType,page=1):Promise<ProviderItem[]>{return this.withHealthyDomain(async base=>{if(!await this.verifyCanonicalDomain(base))return{value:[],identityVerified:false};const p=type==='anime'?'anime':type==='series'?'series':'movies';const r=await this.http.get(`${base}/${p}${page>1?`/page/${page}`:''}`);const b=this.effectiveOrigin(r.url,base);return{value:this.parseItems(r.$,b,type),identityVerified:true};});}
  async getMetaInternal(contentId:string,type:StremioContentType):Promise<ProviderDetail|null>{return this.withHealthyDomain(async base=>{const r=await this.http.get(this.fixUrl(contentId,base));const b=this.effectiveOrigin(r.url,base);const title=r.$('h1.title,h1').first().text().trim()||r.$('meta[property="og:title"]').attr('content')||'FaselHD Title';const poster=this.fixUrl(r.$('meta[property="og:image"]').attr('content')||r.$('article img').first().attr('src'),b);const description=r.$('meta[name="description"]').attr('content')||'';const episodes:ProviderEpisode[]=[];r.$('a[href*="watch.php"],a[href*="/episode/"]').each((i:number,el:any)=>{const href=r.$(el).attr('href');if(!href)return;const t=r.$(el).text().trim()||`حلقة ${i+1}`;episodes.push({id:this.formatId(this.fixUrl(href,b).replace(b,'')),title:t,season:1,episode:i+1,url:this.fixUrl(href,b),poster});});return{value:{id:this.formatId(this.fixUrl(contentId,b).replace(b,'')),provider:this.name,type:episodes.length?'series':type,title,poster,description,url:this.fixUrl(contentId,b),episodes:episodes.length?episodes:undefined},identityVerified:this.identityVerified(r.$)};});}
  async getStreamsInternal(contentId:string,_type:StremioContentType,episodeId?:string):Promise<ResolvedStream[]>{return this.withHealthyDomain(async base=>{const full=this.fixUrl(episodeId||contentId,base);const r=await this.http.get(full,{headers:{'User-Agent':MOBILE_USER_AGENT}});const b=this.effectiveOrigin(r.url,base);const streams:ResolvedStream[]=[];const add=(url:string,name='FaselHD Direct',quality='Auto',headers:Record<string,string>={})=>{if(!/^https?:\/\//i.test(url))return;if(!streams.some(s=>s.url===url))streams.push({name,quality,url,isM3u8:/\.m3u8(?:$|\?)/i.test(url),headers});};
    const scripts=r.$('script').map((_:any,s:any)=>r.$(s).text()).get().join('\n');
    for(const m of scripts.matchAll(/https?:\\?\\/\\/[^"'\\s<>]+(?:\.m3u8|\.mp4|\.mkv)(?:\?[^"'\\s<>]*)?/gi))add(m[0].replace(/\\\\/g,''),'FaselHD Script');
    for(const m of r.text.matchAll(/https?:\\?\\/\\/[^"'\\s<>]+(?:\.m3u8|\.mp4|\.mkv)(?:\?[^"'\\s<>]*)?/gi))add(m[0].replace(/\\\\/g,''),'FaselHD HTML');
    const iframe=r.$('iframe').first().attr('data-src')||r.$('iframe').first().attr('src');
    if(iframe)try{const pu=this.fixUrl(iframe,b);const pr=await this.http.get(pu,{headers:{Referer:r.url||full,'User-Agent':MOBILE_USER_AGENT}});const pscript=pr.$('script').map((_:any,s:any)=>pr.$(s).text()).get().join('\n');for(const m of pscript.matchAll(/https?:\\?\\/\\/[^"'\\s<>]+(?:\.m3u8|\.mp4|\.mkv)(?:\?[^"'\\s<>]*)?/gi))add(m[0].replace(/\\\\/g,''),'FaselHD Iframe','Auto',{Referer:pu});const ctx:any={window:{},document:{getElementById:()=>({})},navigator:{userAgent:'Mozilla/5.0'},jwplayer:()=>({setup:(cfg:any)=>{if(cfg?.file)add(cfg.file,'FaselHD JW','1080p',{Referer:pu});for(const s of cfg?.sources||[])if(s?.file)add(s.file,`FaselHD ${s.label||'Source'}`,s.label||'Auto',{Referer:pu});},on:()=>{}})};vm.createContext(ctx);for(const sc of pr.$('script').map((_:any,s:any)=>pr.$(s).text()).get())if(/jwplayer|sources|eval/i.test(sc))try{vm.runInContext(sc,ctx,{timeout:2000});}catch{} }catch(e){this.logger.debug(`FaselHD iframe extraction failed: ${(e as Error).message}`);}
    const links:string[]=[];r.$('a[href],button[data-href],button[onclick],.serversList a,.buttonsList button').each((_:any,el:any)=>{const h=r.$(el).attr('href')||r.$(el).attr('data-href')||r.$(el).attr('onclick')?.match(/https?:\/\/[^'\"]+/)?.[0];if(h)links.push(this.fixUrl(h,b));});for(const u of [...new Set(links)].slice(0,8))try{for(const s of await extractStreams(u,r.url||full))add(s.url,s.name,s.quality,{...(s.headers||{}),Referer:r.url||full});}catch{}return{value:streams,identityVerified:this.identityVerified(r.$)};});}
}
